### ISSUE TITLE
Contract: Subcontractors

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#392] opened 2016-09-20 19:39 UTC
In #249 we discuss adding `suppliers` to the `contract` object.

From this, @agm3dc has pointed to the use case of wanting to understand subcontractors involved in:
- A bid
- A contract award
- The contract

This is important for certain forms of red flag analysis, such as looking for cases where a loosing bidder appears as a subcontractor to the winning bid.

It is also information that exists in some systems. 

We are looking in #371 at how subcontracting processes might be linked to their parent processes. However, there are cases where no subcontracting process information is available, but the primary contractor is obliged to report their subcontractors.

In #249 we talk of having an array of suppliers, which had suggested we could include subcontractors here and indicate their role. 

However, I think it might be more natural to make `contract.suppliers` solely the parties to the signed contract, and introduce `contract.subcontractors` for named subcontractors.

In the case of a bids extension, we could similarly have `bid.bidders` for the named parties to the bid, and `bid.subcontractors` for those who are named in the bid as potential subcontractors. 

Views on this welcome.

This issue has come in after prioritisation for 1.1, but with enough support could be consider as part of the 1.1 process as it arises from 1.1 discussions. As it would be likely delivered through an extension, this may not be an issue anyway.

**Comment by duncandewhurst** [comment] 2016-10-19 10:21
Comment from Rose Gill Hearn at the Open Contracting day at IODC:
- In New York, the terms **supplier** and **vendor** have specific meaning in the context of sub-contracting - the party that contracts with the procuring entity is known as the **vendor** whilst any sub-contractors are known as **suppliers**

**Comment by duncandewhurst** [comment] 2016-11-14 15:05
The World Bank's [Public Procurement Indicators](http://www.eprocurementtoolkit.org/sites/default/files/2016-10/Public%20Procurement%20Indicators-Rapid_e-Procurement_Toolkit.pdf) for monitoring e-GP adoption and performance includes indicators for **number** and **value** of sub-contracts per contract type.

**Comment by duncandewhurst** [comment] 2017-01-05 14:30
@LindseyAM noted the following reporting requirement in Ukraine:

> apparently in Ukraine, if a subcontractor is responsible for
implementing more than 20 percent of the contract, then the subcontractor’s
name and registration number will be disclosed, as well as the amount of
public funds it spends under the contract.

The proposed ```contract.subcontractors``` array would meet the requirement to disclose the subcontractor's name and registration number whilst ```contract. implementation.transaction``` could be used to disclose the amount of public funds spent by the subcontractor (either directly or by setting ```providerOrganization``` to the primary contractor and ```receiverOrganization``` to the subcontractor)

This issue also picks up the thread from #144

**Comment by duncandewhurst** [comment] 2017-06-27 09:19
In the UK, a true/false ```supplyChain``` field is being added to the Contracts Finder platform to identify sub-contracting processes

**Comment by jpmckinney** [comment] 2018-09-26 18:20
Raised at Standards Day by @kaerumy

For example, in a large infrastructure project in Malaysia, a company might win the construction of the project, then publish opportunities and awards on its own website. In this case, at minimum, the company should re-use and publish the identifier of the project it won, in order to link the disclosures.

**Comment by jpmckinney** [comment] 2018-12-05 01:19
@JachymHercher expressed in #703 the disclosure of, at minimum, the subcontractor (as a party) and what was subcontracted (perhaps as a free-text description of structured `items`).

**Comment by duncandewhurst** [comment] 2019-01-25 15:59
OCDS data from Prozorro includes a string `subcontractingDetails` field on the `bid` object which appears to indicate whether the bidder plans to use sub-contractors.

**Comment by LindseyAM** [comment] 2019-01-26 15:10
@myroslav does ukraine publish details of subcontracts? Will this be included in OCDS publication? Can you advise on this issue?

@duncandewhurst should we also ask andrew's team to share what they are publishing on subcontracts (or planning to publish).

In Los Angeles, information on subcontracts is currently published in paper schedules (so it is a longer term project to digitize) but as I understand in LA a 'prime' contractor must declare an intention to subcontract and then it must later furnish the following information 

Who are subs (schedule a) 
Are they getting paid (schedule b) 
Sum of payments to subs broken out by sub (schedule c)

**Comment by LindseyAM** [comment] 2019-01-28 14:10
@duncandewhurst does oc4infra have subcontractors?

**Comment by duncandewhurst** [comment] 2019-01-28 15:19
The UK's current publication is noted above (the `supplyChain` flag), but we can check if they have any further plans to publish sub-contracting data, or to link contracts and sub-contracts.

OC4Infra doesn't have anything specific for sub-contractors (since the CoST IDS doesn't) but we can consider it for addition if we see demand and whatever approach we settle on for OCDS can likely be ported to OC4Infra.

**Comment by LindseyAM** [comment] 2019-01-29 02:06
Thanks @duncandewhurst - came up in a conversation re manchester today with @herahussain (where potential goal is to publish prime and sub information on an infrastructure project)

OCDS documentation makes multiple references to the possibility of publishing subcontracting information but I didn't see when I searched OC4Infra documentation. Recommend adding some content to the implementation guidance. good to check PPP docs as well

**Comment by duncandewhurst** [comment] 2019-01-31 09:16
UK confirmed they don't have any further plans to publish subcontracting data at present.

I checked with CoST Ukraine and their data model includes the following fields for sub-contracting, however these are based on what they would like to analyse, rather than what is actually being collected by procuring entities:

- Contract No. General Contract
- Contract No. Subcontract
- Date of contract of subcontract
- Organization name
- Organisaion tax №
- Currency of the contract
- The cost of the contract
- % of the contract of the general contract

They also clarified the 20% rule in Ukraine, as follows:

> bidder is not allowed to take part in the tender if he plans to give more than 20% of contract to a sub contractor, there are specific reasons why the 20% could be exceeded but this needs to be approved by the buyer

**Comment by jpmckinney** [comment] 2023-06-07 00:56
The outlook for publication of detailed subcontracting information has not changed since this issue was opened.

That said, there has been some progress in specific jurisdictions leading to new/updated extensions, e.g. the [subcontracting extension](https://extensions.open-contracting.org/en/extensions/subcontracting/master/) will be updated to include the names of subcontractors, which are disclosed as of the eForms regulation.

Nonetheless, without data, there is limited opportunity for standardization in OCDS. So, closing.

**Closed as completed by jpmckinney** 2023-06-07 00:56 UTC
Labels: Focus - Extensions

**Comment by yolile** [comment] 2023-06-07 01:01
Cc @fppenna in case you want to say something about the Portland case
