### ISSUE TITLE
Multiple ContactPoints

### ISSUE THREAD

**Issue by myroslav** [open-contracting/standard#291] opened 2016-01-22 03:55 UTC
We have need to specify contact points for different languages. According to https://schema.org/ContactPoint there is `availableLanguage` just for the purpose. That extension to OCDS is not a problem.

However we need Organization to have multiple ContactPoints. According to https://schema.org/Organization there is `contactPoint` that "Supersedes contactPoints.". In the Google.Org example (see first one from Examples section in lower part of the page) one can see sample of how multiple values are serialized in array and assigned to "singular" property (on alumni example).

Should we have `Organization.contactPoint` to always be collection (even with single element), or to be either individual element of there is only one ContactPoint, and to be array, if there are more of them.

**Comment by kindly** [comment] 2016-01-22 10:34
I always thought that contactPoint should be singular i.e express the "main contact".
I also do not like the mixture or arrays or single elements in the same field.  Also if an extension changed this it would be very confusing for the data consumer.
My opinion would be (even though its different to schema.org) would be to add an extra field "additionalContactPoints" which is an array.  This is much more easily added in an extension and in keeping with some other fields in the OCDS schema.  It also keeps the idea of a "main contact" and at some point could get added to the main OCDS schema without backward compatibility issues.

**Comment by timgdavies** [comment] 2016-01-26 17:25
We discussed this today, and I would agree that `additionalContactPoints` as an array is the OCDS way to capture these, with the OCDS standard `contactPoint` element used either for a primary contact point, or to state that users should consult the full list of contact points, providing a URL to where these can be found.

**Comment by kindly** [comment] 2016-05-05 09:29
Closing this issue as its a duplicate of #266.

**Closed as completed by kindly** 2016-05-05 09:29 UTC
