### ISSUE TITLE
Discussion: Removing objects from an array using the identifier merge strategy

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard#232] opened 2015-09-01 11:51 UTC
http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/reference/#empty-fields desribes how to remove a field, by setting it as null. However, this doesn't work for removing an object from an array that uses the [ocdsVersion](http://ocds.open-contracting.org/standard/r/1__0__0/en/implementation/merging/#ocdsversion-merge-strategy) merge stratergy, because I must include the ID of the object.

E.g. removing items from an item array

Original release:

``` json
{
...
     "items": [
        { "id": 1, "description": "Item 1", "quantity": 1 },
        { "id": 2, "description": "Item 2", "quantity": 1 }
    ]
...
}
```

If I just want to remove item 2, the best I can do is:

``` json
{
...
     "items": [
        { "id": 2, "description": null, "quantity": null }
    ]
...
}
```

which results in this record:

``` json
{
...
     "items": [
        { "id": 1, "description": "Item 1", "quantity": 1 },
        { "id": 2, "description": null, "quantity": null }
    ]
...
}
```

The object I want to remove is still there, and still has an ID, and it's impossible to distinguish a removed item from an item that all the fields have been removed from (this distinction may not matter in practice, but I think it at least makes counting how many items are in a record tricky).

Additionally, to use this approach I must know what every field in the item I wish to remove is. This would be impossible if the item contains information from multiple data sources (although this may not work anyway).

An alternative is to introduce some reserved field that would let the merge tool know that an entire record had been dropped, although this seems at best inelegant.

**Comment by timgdavies** [comment] 2015-09-02 16:07
So - we have two issues here:

(1) Residual entries

As in the case above, item 2 hangs around, just with null values;

(2) Field knowledge requirement

The fact that you need to know all the fields that have been set in order to to set them as null.

It seems to be that (1) can be dealt with my changing the expected merge behaviour to be that:

* If a field has a value of null, it can be dropped from the output (I think this may already be the behaviour?) 
* If an object only has an ID, it can be dropped from the output (this would be a new behaviour)

This doesn't however deal with (2), which would need either:

(a) An application simple sets as null all possible fields of the item (whether or not they have been provided before) - a bit clunky, but would work;

(b) We introduce the reserved field @Bjwebb suggests above - although, as noted, this is inelegant.

So the choice here might be between clunky or inelegant... not sure we've another good option..

**Comment by LindseyAM** [comment] 2015-09-08 19:34
@Bjwebb @timgdavies Hi Both, I am not sure I understand what the problem is here that is trying to be solved. Can you explain?

**Comment by timgdavies** [comment] 2015-09-09 16:32
@LindseyAM 

Imagine a scenario in which you are planning to procure:

* Item A: 100 lightbulbs;
* Item B: 100 light fittings;

and you include them in a release. You then decide you only want to split these into two tenders, so you put out an updated release, cutting the light fittings out from the first tender. You now want the record to just contain:

* Item A: 100 lightbulbs

This means the later release needs to 'unset' the previous 'Item B'. It cannot just omit this, because then the record will still contain Item B. 

Our current model only allows you to blank out Item B, so you would have:

* Item A: 100 lightbulbs 
* Item B: blank

Which is inelegant. 

Does that help clarify?

**Comment by birdsarah** [comment] 2015-09-09 17:38
Not sure about approach, but definitely want this to err on the side of glaringly ugly. Because it seems like exactly the kind of thing you'd want to trace/rejoin/etc.

What about keeping all the info, but setting the quantity to -1 or a reserved value - or even the new releaseid? (This is going to confuse some people).

**Comment by timgdavies** [comment] 2016-05-20 12:50
@kindly Can you have a look at this issue and discuss with @bjwebb to identify if some action is required?

**Comment by kindly** [comment] 2016-06-14 11:27
Another solution:

c)
If you want to remove an object just supply the id only in that object and no other fields.

Original release:

``` json
{
...
     "items": [
        { "id": 1, "description": "Item 1", "quantity": 1 },
        { "id": 2, "description": "Item 2", "quantity": 1 }
    ]
...
}
```

To remove item 2:

``` json
{
...
     "items": [
        { "id": 2 }
    ]
...
}
```

which results in this:

``` json
{
...
     "items": [
        { "id": 1, "description": "Item 1", "quantity": 1 }
    ]
...
}
```

I would say this is neither inelegant or cluncky but could be considered counter intuitive and have a small chance of happening by accident.

**Comment by timgdavies** [comment] 2016-08-03 16:03
Following discussion, I think we are close to consensus on [solution c](http://standard.open-contracting.org/latest/en/schema/reference/#empty-fields) from @kindly.

The reasoning for this choice is that:
- Option (a) of requiring everything to be set to null requires too much knowledge about all the fields that did exist;
- Option (b) of an explicit field to indicate deletion of an object in the array (e.g. `"removed":true`) requires this to be added to all the objects in the schema. 

Whereas option (c) requires no additions to the schema. There is a risk of ambiguity if a publisher provides data (including changed data!) alongside a `"removed":true`` property. 

We considered the risk of accidental provision of empty id objects in a list to be low. 

We recognise that some publishers do not keep a log of items removed (or only include this in an audit table of their systems). We may need to develop further guidance for these cases as part of the technical support process.

## Actions

This would require an [update to empty fields section of the documentation](http://standard.open-contracting.org/latest/en/schema/reference/#empty-fields)

It would benefit from the addition of examples in the documentation and updates to the technical mapping templates provided by the helpdesk.

It requires updates to the reference implementation of the merging tool, which @kindly will explore. 
- [x] Confirm proposal with community
- [ ] Develop updates to merge tool (@kindly)
- [ ] Develop worked examples for documentation (?)
- [ ] Develop proposed changes to documentation (@timgdavies)
- [ ] Update helpdesk technical assessment templates (@timdavies)

**Comment by timgdavies** [comment] 2017-01-27 16:00
We've identified that this creates problems for required fields. Approach needs further review. Tim to discuss with @kindly

**Comment by timgdavies** [comment] 2017-02-08 12:50
Only issue is with awardID being required.

**Comment by jpmckinney** [comment] 2017-08-26 02:09
This issue has not been resolved. Moving to a new milestone and reopening.

**Comment by jpmckinney** [comment] 2018-02-08 14:57
@timgdavies With https://github.com/OpenDataServices/cove/issues/947 moving forward, should we discuss this as well?

**Comment by yolile** [comment] 2019-11-14 13:50
I think that the only problem with solution c it is that you have to know the id of the deleted item and that may not be the case if dont you produce your releases in real time or if you dont keep the changes history of the items or if you do it, it can be a little messy to compare the old items with the new ones and identify and add the id of the deleted one.

Another option could be to always publish the **full list of items**. Something like:

Original release
```json
{
  "items": [ 
    {
      "id": "1",
       "description": "item 1"
    },
    {
      "id": "2",
       "description": "item 2"
    },
    {
      "id": "3",
       "description": "item 3"
    }

  ]
}
```

And to remove item 2, just remove it from the list:

```json
{
  "items": [ 
    {
      "id": "1",
       "description": "item 1"
    },
    {
      "id": "3",
       "description": "item 3"
    }
  ]
}

**Comment by jpmckinney** [comment] 2019-11-14 15:03
@yolile But then it becomes impossible to just update one entry in the array, no?

**Comment by yolile** [comment] 2019-11-14 15:19
No, because we could still use the items.id for the updates

**Comment by jpmckinney** [comment] 2019-11-14 15:34
@yolile Let's say there's a tender notice with multiple lots, and each lot is awarded in a separate award notice. The first award notice has:

```
{
  "awards: [
    {
      "id": "1",
      …
    }
  ]
}
```

Then the second award notice has:

```
{
  "awards: [
    {
      "id": "2",
      …
    }
  ]
}
```

If the entire array needs to be published every time, then (under your proposal) the data for the second award notice deletes the data for the first award notice.

In some systems, individual notices are not aware of prior notices, and so it would be an additional (and unnecessary) difficulty to have to find and add the data for the first award notice when preparing the data for the second award notice. Individual releases would also become huge for framework agreements and for catalogue purchases, where the number of contracts / purchase orders is very large.

That's why there is an identifier-merge strategy in OCDS, instead of always requiring that everyone publish entire arrays, every time.

**Comment by yolile** [comment] 2019-11-14 16:01
> In many systems, individual notices are not aware of prior notices, and
so it would be an additional (and unnecessary) difficulty to have to find
and add the data for the first award notice when preparing the data for the
second award notice.

But with the current approach or with option c, if you want to delete the
award 1 you have to find its Id anyway, right?

**Comment by jpmckinney** [comment] 2019-11-14 16:08
It's expected that adding a new award (or any other entry in an array that uses identifier-merge) is much more common than removing an award.

With option (c), you need to find the `id` of only the entry you want to remove – which might be difficult, but at least it's rare.

With your proposal, you need to find all the `id`'s of all entries you want to keep, every time you add a new entry – which is even more difficult and much more common, and it makes the release huge (imagine a framework agreement with thousands of direct call-offs).

**Comment by yolile** [comment] 2019-11-14 16:43
> In many systems, individual notices are not aware of prior notices, and so it would be an additional (and unnecessary) difficulty to have to find and add the data for the first award notice when preparing the data for the second award notice

I dont agree (or at least I've never seen this) with this but ok, lets say that it is better no force the publishers to publish the whole list just for the removal issue that, we agree, is not common. 

But we have to keep in mind, as you also said, that no all the systems has the information about the previous items or the deleted ones, in which cases the current aproach will not work.

**Comment by jpmckinney** [comment] 2019-11-14 17:04
Yes, we don't yet have a proposal for removing entries in arrays that meets all these criteria:

1. The proposal is backwards-compatible with the existing merging rules (otherwise, we need to wait for OCDS 2.0)
1. The proposal respects the design of OCDS of allowing incremental updates, i.e. without having to publish every entry of a given array, every time
1. The proposal allows publishers to delete entries whose `id` is not known at the time that the update is made

If you have a new proposal that at least meets the first criterion, it can be an option for OCDS 1.2.

**Comment by romifz** [comment] 2020-02-06 19:14
After reading the whole thread, I have a few doubts.

I understand that setting all the fields in the array item to `null` is not a proposal to remove array items for the moment, but could it be? That way it could be included in the merge routine and it would allow to remove items from arrays.

If so, what happens with the fields that have an object as value? Should the publisher declare the field as `null`, as in
```
"items": [{
  "classifications": null,
  ...
}]
``` 
or each object field should be set to `null`, as in
```
"items": [{
  "classifications": {
    "scheme": null,
    "id": null,
    ...
  },
  ...
]}
``` 
Should the publisher declare as `null` all the fields they use, or all the fields in the schema for that item? For example, should they declare as `null` `additionalClassifications` if they never use it? I would believe it's better to consider the previously declared fields only, because this would include any additional fields or extensions used.

Tim mentioned there is an issue with `awardID` being required. I think required fields can be ignored (a contract with `id` and `awardID` only does not provide any useful information), but I don't know the criteria used to set a field as required, so this could not be a good idea.

**Comment by jpmckinney** [comment] 2020-02-07 03:12
An object can't be set to `null`, because it would change the behavior of the versioned release: instead of versioning each 'leaf' field individually, it would have to version the entire object as a whole (since its value can be changed to `null`). If, for example, `tender` were versioned as a whole, that would make the versioned release much less useful (and much more bloated).

@romifz I think you're proposing option (a), but it seems like more work than option (c).

For my part, I don't like any option and would like to consider other options (perhaps looking to see how JSON-LD indicates deleted nodes), but option (c) seems the simplest.

**Comment by romifz** [comment] 2020-02-07 14:12
I now option (a) is more work, but it is also consistent with the advice given in [OCDS documentation](https://standard.open-contracting.org/latest/en/schema/merging/#identifier-merge) so far. But I do agree that there may be better options.

**Comment by jpmckinney** [comment] 2020-07-01 19:38
We might want to have a special tag e.g. 'correction', which (if present) applies different merge rules to allow deleting objects in arrays. We might go even further and only delete fields that are set to null if the special tag is present. In other words, publishers explicitly opt-in to deleting existing data; currently, most use of `null` is accidental.

**Comment by jpmckinney** [comment] 2023-06-06 20:07
We have not witnessed any demand for this feature.

In reality, it's not expected for publishers to delete entries from arrays. The only exception we've witnessed is where a publisher releases confidential information, which they then need to redact. However, in that scenario, the only option is to delete and re-publish the release, as otherwise the confidential information will remain available.

So, closing.

**Closed by jpmckinney** 2023-06-06 20:07 UTC
Labels: Schema, Focus - Merging, discussion
