### ISSUE TITLE
`procurementMethod`: improve description and documentation

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1395] opened 2021-08-26 20:21 UTC
We should improve the information around `procurementMethod`: 
1) The current description is 
    > The procurement method, from the closed method codelist.

    Which doesn't say much. I would suggest something like: or "The procurement method sets out the organizations that are allowed to submit a bid."    

2) In the text in https://standard.open-contracting.org/1.1/en/schema/codelists/#method, I would remove at least the first sentence "A contracting process aims to fulfill the requirements identified at the planning stage." Concerning the note, see https://github.com/open-contracting/standard/issues/1396. 

3) In line with https://github.com/open-contracting/standard/issues/1301#issuecomment-906715985, we should add a sentence to the description along the lines of "In releases concerning second stages (e.g. in  framework agreements) or other subsequent stages, the procurement method always refers to the first stage of the process."

**Comment by jpmckinney** [comment] 2021-08-27 14:12
How about:

> The procurement method describes which organizations can submit a bid.

For the second stage, I don't know anymore. We will need specific guidance whether the field's value mirrors the first stage or is about the second stage. My original objection is here: https://github.com/open-contracting/standard/issues/1301#issuecomment-862012507 However, my understanding now is that the issue isn't about conditional semantics, but about being clear as to which of two interpretations is correct. The field can either be about the current OCID, or about the over-arching contracting process that has no representation in OCDS 1.X. Looking at it now, it seems more unusual for the field to be about the over-arching contracting process, because we don't do that for any other field. So, I think it might be best to have it be about who can submit a bid in the second stage. If that is the case, then we might be able to remove the need for the `competitive` field.

@yolile @duncandewhurst for thoughts, since we want the decision here to not change again.

We have shared the current guidance with a few partners, but we can discuss how to address that in a second step.

**Comment by jpmckinney** [comment] 2021-08-27 14:18
In the OCDS for EU profile, a contract award notice describes the procurement method. Since the EU properly models call-offs as part of the same contracting process, its fields do refer to the first stage: https://standard.open-contracting.org/profiles/eu/latest/en/forms/F03/#section-iv To my knowledge, the old forms have no way to indicate who can submit in the second stage.

So, for consistency, it maybe is better to keep the interpretation as referring to the over-arching contracting process, and to update the description like in point (3).

**Comment by JachymHercher** [comment] 2021-08-27 17:18
Summary: Shouldn't the semantics for `procurementMethod` be specific to a single stage because it will be easier to compile and analyze? (That being said, I'm not a big fan of `competitive`, because it is semantically the same thing as `procurementMethod`, just in a different stage, and this link is not there. Can't we have 2-3 fields called procurementMethod#?) 

____

Thinking out loud (useful for thinking further on): processes can have multiple stages, but I _think_ a process can involve at most two subsequent procurement methods, because the one that applies to the second stage also applies to all the subsequent stages. 

Exhaustive list of cases:
- framework agremeents (FA) - typical:  
    - 1st: 'open'/'selective'/'limited'/'direct' 
    - 2nd: 'limited' ("all suppliers qualified _in the previous round_ can now submit a tender") /'direct' (classical FA with one supplier per lot). 
        - You cannot have 'open', because the suppliers are limited by the 1st stage. 
        - I have never seen 'selective' in the second round, so I'm putting it here. However, I think there are plausible theoretical cases, e.g. "in the first round, we've selected companies with turnover EUR 1M into our bridge building FA. In this second round competition, we're building a really big bridge, so you need a turnover of EUR 2M, i.e. were essentially doing a second round of qualification". No idea if this exists somewhere in the world, happy to assume it doesn't until someone comes up with it.

- framework agreements (FA) - alternative:
    - 1st round: e.g. "Companies, submit your requests to participate to get qualified (e.g. selection criterion: turnover > EUR 1M)". ('selective')
    - 2nd round: "Qualified companies, submit your bids to get into the FA (e.g. award criterion: maximum manhour price) ('limited')
    - 3rd round "Companies inside the FA, submit your call-off bids to get an actual contract (e.g. award criterion: the actual manhour price for this contract). ('limited') 

    As far as I know, the 1st and 2nd rounds happen typically together (and then they are "FA - typical"). However, I think it might be possible for them to also happen separately, as described here. Happy for confirmation. 

 - innovative partnership / competitive dialogue: 
    - 1st: 'open'/'selective'/'limited'/'direct'
        - In the EU, reading the law rather strictly, 'open' would not be an option, as it seems as if qualification would be a mandatory part of it. However, I don't see any reason why it would and it seems as an idiosyncrasy of legal drafting, so I'm assuming somewhere in the world it is possible, so I would leave 'open' as an option. 
    - 2nd _and all subsequent_: 'limited' ("all suppliers qualified _in the previous round_ or those that survived the previous round of eliminations (reducing the number of competitors round by round) can now submit a tender")

Terminological note (maybe useful, maybe not): 
- I see FA as having at most 2 or 3 rounds, i.e. I see 10 subsequent call-offs as 10 different instances of a 3rd round.
- I see innovatiave partnershisp / competitive dialogues as potentially having many rounds - 1,2,3,4,5,6...

____

> For the second stage, I don't know anymore. We will need specific guidance whether the field's value mirrors the first stage or is about the second stage. My original objection is here: #1301 (comment) However, my understanding now is that the issue isn't about conditional semantics, but about being clear as to which of two interpretations is correct. The field can either be about the current OCID, or about the over-arching contracting process that has no representation in OCDS 1.X. Looking at it now, it seems more unusual for the field to be about the over-arching contracting process, because we don't do that for any other field. So, I think it might be best to have it be about who can submit a bid in the second stage. If that is the case, then we might be able to remove the need for the competitive field.

Practically, wouldn't the main point of different fields be easier reuse? If we are trying to facilitate the analysis of data based on a single record, then we can't use `procurementMethod` in each round, because - in OCDS 2.0, once we have all stages in one process -
only the last one would stay, right? By contrast, since there can be at most 2/3 procurement methods in a process, having a `procurementMethodStage1`, `procurementMethodStage2+` (or possibly one more) seems feasible? 

More abstractly, and going against the previous point, I don't share/have the idea of an "over arching process". I see stages as linear, as of equal value. In particular for innovative partnerships and competitive dialogues, I'd argue the 1st stage is no more special than the 7th. And if we see them as equal for innovative partnerships, it is more universal to also seem them more equal for framework agreements.

___

> In the OCDS for EU profile, a contract award notice describes the procurement method. Since the EU properly models call-offs as part of the same contracting process, its fields do refer to the first stage: https://standard.open-contracting.org/profiles/eu/latest/en/forms/F03/#section-iv To my knowledge, the old forms have no way to indicate who can submit in the second stage.

Correct. (The new forms specify whether a FA is "with reopening of competition" or "without reopening of competition".)

> So, for consistency, it maybe is better to keep the interpretation as referring to the over-arching contracting process, and to update the description like in point (3).

I'm not sure. EU forms are not clear on the semantics ("over-arching" vs. "1st stage"), so there isn't a problem with semantic consistency? Furthermore, EU forms have tons of unnecessary repetition across notices, which I would consider a bug rather than a feature, so it's something we can avoid in OCDS. When going from eForms/TED 2.0.9 to OCDS 1.X, for FAs, you'll have to have one release for "award of FA" and one release for "award of contract within FA", each as a part of a different process, regardless of the semantics of `procurementMethod`. In the opposite direction, you would just ignore the `procuremntMethod` in the "award of contract within FA" release, so there shouldn't be a consistency problem from a "structural" point of view either?  

____
____

> The procurement method describes which organizations can submit a bid.

It's fine. Totally splitting hairs, feel free to ignore:
- "describes" vs. "sets" - I see notices as having legal power, i.e. actually setting who is and who is not allowed to do things. This is probably not appropriate in the OCDS context.
- "can" vs. "are allowed" - "can" sounds to me as "can push the "send" button" while "are allowed" more as what it is - the buyer allowed them to do something (i.e. promised he'll read it if he gets it :) ).

**Comment by yolile** [comment] 2021-08-27 18:38
> So, for consistency, it maybe is better to keep the interpretation as referring to the over-arching contracting process, and to update the description like in point (3).

In terms of data use, we came across something similar to this while using the Chile data in the BI Tool. The main question to answer was: for the openness indicators, should the purchase orders from a framework agreement be counted as open procedures or not? As the process for selecting the suppliers was open, we considered that the purchase orders should be treated as open as well. Therefore, implicitly we used the same procurement method for both, the framework agreement set up and for the purchase orders.

**Comment by jpmckinney** [comment] 2021-08-27 18:44
For the purpose of thinking this through, I think the definitions are better read as:

* selective: All interested suppliers can qualify to submit a bid.
* limited: Only invited suppliers can submit a bid.

Otherwise, when thinking about the second stage, selective ("Only qualified suppliers are invited to submit a bid") sounds more correct than limited ("The procuring entity contacts a number of suppliers of its choice."), since it is true that only qualified suppliers are bidding in the second stage, and it is not true that the procuring entity decides which of those qualified suppliers get to bid.

If this is an important clarification to make, we should open an issue for the method codelist.

----

Regarding "framework agreements (FA) - alternative", a selection step (in any procedure using any technique) always implies a limited invitation – i.e. whenever there is qualification, it is only those qualified who can then submit a bid – so I don't think it is appropriate to separate these into stages with respect to information disclosure. They are just one stage. (e-GP process modelling can separate them since you need to send out invitations, etc., but that approach would sub-divide pretty much everything in OCDS anyway). 

Dynamic purchasing systems are a type of FA (at least in the broad international/academic analysis). I don't know if in the above analysis DPSes are treated as having a perpetually-open first stage, if a stage is missing, or if the second stage is in fact open or selective.

----

By "over-arching contracting process" I mean the thing that contains all the stages. With respect to competitive conditions, the conditions at the first stage have an overwhelming influence over the competition in the remaining stages. The first stage is special in this respect.

In OCDS 2.0, we can have a first-stage object, and then multiple second-stage objects, each of which has its own field for communicating its competitive conditions, so there would not be a conflict/overlap. However, speculating about OCDS 2.0 is not informative for this issue, because OCDS 2.0 might be anything (XML/RDF, etc.).

**Comment by JachymHercher** [comment] 2021-08-27 20:24
> Regarding "framework agreements (FA) - alternative", a selection step (in any procedure using any technique) always implies a limited invitation – i.e. whenever there is qualification, it is only those qualified who can then submit a bid – so I don't think it is appropriate to separate these into stages with respect to information disclosure. They are just one stage. (e-GP process modelling can separate them since you need to send out invitations, etc., but that approach would sub-divide pretty much everything in OCDS anyway).

I guess this leads to the question "what is a stage?" The first thing worth noting is that we have stages in the sense of "planning", "tender" etc. (discussed e.g. in https://github.com/open-contracting/standard/issues/1385); and we have "stages" in the sense of "first stage competition" and "second stage competition" (in https://standard.open-contracting.org/1.1/en/guidance/map/related_processes/#). The latter corresponds to the EU's "single stage procedure" (= open) and two-stage procedures (everything else). 

My interpretation of the stage in the "two stage procedure" sense would be "steps when competition takes place / when we reduce the number of potential suppliers". In the two FA scenarios, the choice/reduction of companies/tenderers happens at different moments / in different ways and since company selection is important, I'd expect we would like to publish data about it... (Assuming the FA-alternative scenario is real.)

_____

> Dynamic purchasing systems are a type of FA (at least in the broad international/academic analysis). I don't know if in the above analysis DPSes are treated as having a perpetually-open first stage, if a stage is missing, or if the second stage is in fact open or selective.

Above I assume they are part of FA; I'd treat them as a perpetually-open first stage = a first stage that overlaps with the second stage.

_____

> By "over-arching contracting process" I mean the thing that contains all the stages. With respect to competitive conditions, the conditions at the first stage have an overwhelming influence over the competition in the remaining stages. The first stage is special in this respect.

I guess the questions is whether it is "special enough" to merit some special treatment. For example, for innovative partnerships I'd say it's much less special than for FA. Generally, I see it similarly as you wrote, which, if I put it in "RDF" triplets, would be contracting processes _have_ stages; stages _have_ procurement methods. Notably, a process would not directly _have_ a procurement method.

**Comment by JachymHercher** [comment] 2021-08-27 20:33
Going back to the point of reuse - thinking of OCDS 1.X, do we have an idea of how users will be working with FAs split into independent processes? Would this be easier with one or the other approach to the definition of `procurementMethod`? 

My impression is that since they will be separate, then probably not - both are workable. In which case we are back to the "talking about over-arching stuff is unusual" vs. "does this introduce inconsistency" arguments.

**Comment by JachymHercher** [comment] 2021-08-28 10:11
> If this is an important clarification to make, we should open an issue for the method codelist.

I've opened a placehoder in https://github.com/open-contracting/standard/issues/1399.

**Comment by jpmckinney** [comment] 2021-09-02 04:30
I am at a point of not liking any of the solutions, in which case my preference is to leave this as-is with respect to the `procurementMethod` value being the same across all stages, call-offs, etc.

If that's alright, we can proceed with the items in the issue description.

**Comment by duncandewhurst** [comment] 2021-09-20 22:31
> Going back to the point of reuse - thinking of OCDS 1.X, do we have an idea of how users will be working with FAs split into independent processes? Would this be easier with one or the other approach to the definition of `procurementMethod`?

I think @yolile's comment in https://github.com/open-contracting/standard/issues/1395#issuecomment-907397774 is the only example we have of using data about FAs. I suspect that how users want to treat FAs might come down to the type of analysis they are doing, so I think the main thing is to have a clear way of distinguishing FAs from other types of procedure, which is addressed in the FA guidance.

> I am at a point of not liking any of the solutions, in which case my preference is to leave this as-is with respect to the `procurementMethod` value being the same across all stages, call-offs, etc.
> 
> If that's alright, we can proceed with the items in the issue description.

That's alright with me. It means that a 'dumb' analysis of the data, which doesn't account for which awards resulted from FA procedures, would align with @yolile's feedback.

**Comment by JachymHercher** [comment] 2021-09-21 14:48
> I am at a point of not liking any of the solutions, in which case my preference is to leave this as-is with respect to the procurementMethod value being the same across all stages, call-offs, etc.

I have prepared the PR based on "leaving as-is". I am very unsure whether it's the best "long term" solution, but I don't have a clear idea on a better one and if it's not, it'll come back to haunt us later on, so we can deal with it then.

**Closed as completed** 2021-09-21 19:27 UTC
Labels: Focus - Documentation, Semantics
