### ISSUE TITLE
Clarify how release/id in a compiled record should be populated

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#745] opened 2018-08-14 15:32 UTC
The schema for a compiled release includes the `release/id` property, but it's not clear whether this field should be provided and how it should be populated since `"omitWhenMerged": true` and the merging rules state

> These properties should be dropped from the merged record - as they only make sense in the context of a single release.

**Comment by jpmckinney** [comment] 2018-09-18 22:23
My understanding is that it shouldn't be populated in `compiledRelease`.

**Comment by jpmckinney** [comment] 2018-09-18 22:50
Marking duplicate of #330.

**Closed as completed by jpmckinney** 2018-09-18 22:50 UTC
Labels: Focus - Documentation
