### ISSUE TITLE
Contracting process' sector

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#399] opened 2016-11-04 16:54 UTC
During the Open Contracting workshop at CONDATOS 2016 in Colombia, a user need for contract 'sector' was raised. 

There was discussion over how this could be identified, from:

* Inferring from the line items (tricky to do: is a computer for health, education or security?);
* The objects of the contract (high level contracting descriptions) - this would need some extraction from text;
* The buyer (e.g. ministry of health)

The extension of OCDS to support the World Bank PPP Framework will likely have [an explicit sector field](https://github.com/open-contracting/public-private-partnerships/issues/22) and this could be considered as an optional extension for the main OCDS  as well.

Views on this issue are welcome. Does explicit 'sector' information exist in government systems? Is there as strong enough use case for sector coding contracts? What codelists might start coming into play if so?

(This is a post 1.1 issue)

cc @juanpane

**Comment by joshuacpowell** [comment] 2016-11-04 17:06
Would be in favor of this, provided we use an open codelist. Each country/gov typically will have their own internal sector classifications, or may use pillars of national planning frameworks (developing country context), SDGs, etc. I think trying to manage/enforce codelists would be difficult, but agree that the field is useful.

**Comment by chrisalexsmith** [comment] 2016-11-09 19:59
The following UN open code list may be of interest as it classifies the functions of government and could be used to map procuring entities. As governments tend to purchase a lot of common use items this would be easier than trying to derive it from the object of the contract particularly as there could be multiple items covered by the contract.

http://unstats.un.org/unsd/cr/registry/regcst.asp?Cl=4&Lg=1

**Comment by timgdavies** [comment] 2016-11-11 12:27
Thanks @chriscrownagents - this is a really good suggestion (COFOG) - not least as I believe lots of other lists are mapped to it. In the work we're doing on PPP extension I'm suggesting we introduce 

`planning/project/sector` as a `classification` block with COGOG as the recommended classification, and then also have an `additionalClassifications` array where other project categorisations can go. 

This would be still be post 1.1 (as it also involves the refactor of projects and budgets that #400 asks for)

**Comment by juanpane** [comment] 2016-11-17 12:04
for me the real issue is not what code list to use (which can and should be reused from open code lists), but how to actually have this data.
From the CONDATOS session, it was not clear how to get to this data, besides trying to infer this from ready the call for tender or the contract
Any ideas?

**Comment by chrisalexsmith** [comment] 2016-11-18 07:02
With the increasing adoption of e-GP, which will be the main repository for OC data,  it should be possible to  classify the contracting authority by its government  function which should not be difficult to establish once the parent ministry as been identified i.e.  a school normally  falls under Ministry of Education.
In fact this mapping and data may already be held in the government finance system. I don't think it is possible to infer this from the object of the contract as in many cases there will be a 1 to many relationship between the object of the contract and the contracting authority.

**Comment by jpmckinney** [comment] 2018-08-24 15:57
This issue seems to be mainly about inferring the 'sector' of the contracting process from the identity of the contracting authority, and doesn't suggest cases where the 'sector' of the process would be different from that of the authority. That means it's a duplicate of #269, so closing.

FYI, https://github.com/open-contracting-extensions/ocds_ppp_extension adds `planning.project.sector` for cases where the sector is determined independent of the contracting authority's identity. We can consider whether to extract that field from that extension (which, at present, should only be used as part of the full PPP profile!).

**Closed as completed by jpmckinney** 2018-08-24 15:57 UTC
