### ISSUE TITLE
TED Contract Objects Mapping to OCDS

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#279] opened 2015-12-15 18:51 UTC
The EU Tenders Electronic Daily forms for Prior Information Notices and Tenders include a section on the 'object' of a contract (Section II).

Section II can be repeated up to 100 times. 

It contains many of the details that live in the OCDS `tender` object. See [Form 01 for an example](http://simap.ted.europa.eu/documents/10184/99173/EN_F01.pdf) or the image below for details of what this section contains.

In OCDS the main repeated object is `item` rather than tender (we assume overall values, dates and so-on are set at the tender rather than sub-item level). 

This raises a number of question for TED<->OCDS mapping:
- Should we map each OBJECT_CONTRACT element in TED to a separate OCDS contracting process? 
- Should we extend `items` to allow item level specification of the properties TED §II contains?
- Should we re-use the Tender object, allowing an array of `additionalObjects` as a way of modelling the TED case?
- How often do TED notices exist which vary information such as notice dates at this object level? 

![screen shot 2015-12-15 at 18 46 18](https://cloud.githubusercontent.com/assets/342624/11820399/49c8cca8-a35c-11e5-8edf-47b32e3cbefd.png)

**Comment by woodbine** [comment] 2015-12-16 12:10
The problem is that much of the real value in contract data is defined by linking it to the advert and tender documentation that went before it. In theory, there should be, some sort of pre-cursor to any contract, even when that contract emerges as a call-off on a framework. So, in theory there should be a one to one relationship between a tender specification and a contract award object, but in the land of TED, you're not required to issue a new requirements spec when you add an additional contract, so you're never going to get one-to-one relationships, instead you're going to have to live with a one-to-many relationship between the tendered requirements and the OBJECT_CONTRACT. 

If we map each OBJECT_CONTRACT from TED to a separate contracting process, can we still have a one-to-many relationship. If not, we shouldn't go for this option.

My gut preference is to extend `items` as most of these data points are transferrable to other data sources (all except the EU funds references). 

Ian

**Comment by timgdavies** [comment] 2015-12-17 12:10
Ok. I've been looking at this more and I see that:

* The entire Section II (Object) can only be repeated in Form 01 - Prior Information Notices.

In forms 02 and 03 (Tender and Award), only II.2 (item description) can be repeated.

If we assume then that a single Form 01 in TED could relate to multiple OCDS contracting processes, but that tender and award forms will only ever relate to one, this would make modelling in OCDS simpler.

We do have an outstanding challenge in OCDS of how best to capture planning stages, as planning often results in a bundle of contracting processes (which is what the TED PIN form seems to envisage) - each with their own unique tender stages. 

Form 01 schema
![image](https://cloud.githubusercontent.com/assets/342624/11869287/867adbcc-a4b6-11e5-870a-382c54c2d131.png)

Form 02 schema
![image](https://cloud.githubusercontent.com/assets/342624/11869305/ac7adf7a-a4b6-11e5-9321-48694d6cc814.png)

**Comment by woodbine** [comment] 2015-12-17 13:07
Hi Tim,

Re. the planning stages, this might seem like an egregious hack, but could we add planning docs as a document attached to a `tender` object, whilst adding only limited information to the `tender` element (such as Contracting Body, date etc) in the first instance? Hopefully a more detailed set of information can be added to the `tender` once any subsequent forms are published. 

Planning is very much a European anomaly, in that there's a formal process for pre-market engagement, this is not a universal practice, and it might be overkill to try and extend the standard to accommodate it. If there was either a) lots of planning documents being published or b) evidence that other governments are formalising pre-market engagement, then it would be worth adapting the standard, but I think it would be overkill at the moment.

After all this is just more evidence that TED is actually a document repository built around a legal framework, rather than a dynamic tendering / purchasing tool.

Ian

**Comment by timgdavies** [comment] 2015-12-17 13:11
All releases can contain a planning block which [has an array for documents](http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/reference/#planning), so encouraging information to be shared there at the planning stage would make a lot of sense. 

I know getting more information on planning around the world is certainly an Open Contracting ambition - so agreed that we don't want to just standardise on the UK case, but get a broader conversation going about how best to model information for users in a wide range of context.

**Closed** 2017-06-15 11:43 UTC
Labels: TED Mapping
