### ISSUE TITLE
OCDS Version Number in OCDS Releases

### ISSUE THREAD

**Issue by ekoner** [open-contracting/standard#344] opened 2016-06-17 07:58 UTC
As a data analyst, the version number in the OCDS release would confirm which version of the schema the release was compiled against. It would allow me to distinguish between a release at a lower version from errors in a release at a higher version.

**Comment by Bjwebb** [comment] 2016-06-17 08:05
Is this the same issue as https://github.com/open-contracting/standard/issues/301 ?

**Comment by timgdavies** [comment] 2016-06-24 14:06
Yep - duplicate of #301

**Closed as completed by timgdavies** 2016-06-24 14:06 UTC
