### ISSUE TITLE
Clarify definition of hasEnquiries 

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#196] opened 2015-03-03 17:24 UTC
The current definition of 'hasEnquiries' is not terribly clear. We should look back and use cases and more clearly define this:

* hasEnquiries - A Yes/No field to indicate whether enquiries were part of tender process - boolean

**Comment by timgdavies** [comment] 2016-06-13 02:09
@lmarchessault could you suggest an improved definition for hasEnquiries?

**Comment by robredpath** [comment] 2016-08-03 13:45
This is a duplicate of #259 , I think.

**Comment by timgdavies** [comment] 2016-08-03 20:46
Agreed. We can close this ticket and pick up definition issues in #259.

**Closed by timgdavies** 2016-08-03 20:46 UTC
Labels: 1 - Discussion, Focus - Documentation, Focus - Field
