### ISSUE TITLE
Clarify unit description

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1343] opened 2021-07-21 18:15 UTC
Current:

> A description of the unit in which the supplies, services or works are provided (e.g. hours, kilograms) and the unit-price

From the research for the medicine extension, ISO-11240 (Health informatics — Identification of medicinal products — Data elements and structures for the unique identification and exchange of units of measurement) notes:

> Units of measurement shall be distinguished from other notions of the word “unit”, such as counted entities or “units of presentation”.

> NOTE 1: Units of presentation are conventional terms that can be used to describe the properties of a pharmaceutical product, e.g. tablet, vial, puff. They are not the same as units of measurement. Units of measurement are always defined through some reference quantities, which units of presentation are not.

> NOTE 2: Concepts like “tablet”, “patch”, “bottle”, etc., are often used to characterize the various types of countable items. In the context of measurements, they simply represent the quantity “1”, corresponding to the number of items they represent.

In the current description, we only give units of measurement as examples. We also use "unit(s) of measure" in the description of the unit's `scheme` and `uri`.

However, in practice, governments specify goods using both units of measurement and units of presentation, e.g. "5 pallets of toilet paper", "1 ton of gravel", etc.

As such, we should clarify the descriptions to explicitly allow for both types of units. We can also check that the classification scheme codelist covers units of presentation.

**Comment by yolile** [comment] 2022-02-01 18:05
> We can also check that the classification scheme codelist covers units of presentation.

From [The NASA QUDT Units Ontology](https://www.qudt.org/qudt/owl/1.0.0/unit/): The QUDT Units Ontology provides a vocabulary for describing **units of measure**.

UN/CEFACT Recommendation 20 list is for 'Codes for **Units of Measure** Used in International Trade' and https://tfig.unece.org/contents/recommendation-20.htm says:  "this Recommendation establishes a single list of code elements to represent units of measure for length, mass (weight), volume and other quantities (including units of count)." Moreover, this list is mainly based on the [International System of Units](https://en.wikipedia.org/wiki/International_System_of_Units)

So both schemes cover only units of measure, not presentation.

> As such, we should clarify the descriptions to explicitly allow for both types of units.

Should we instead discourage using this field as the unit of presentation and clarify that it is intended for the unit of measure only?

**Comment by jpmckinney** [comment] 2022-02-01 18:18
I think we will have to check how the field is being used – if many publishers are using it for unit of presentation, then it is harder to change the semantics now.

I agree that those schemes are about units of measure, but a publisher could use the field with a scheme for units of presentation (or no scheme).

**Comment by yolile** [comment] 2022-02-02 17:55
[unit_name_use.txt](https://github.com/open-contracting/standard/files/7988523/unit_name_use.txt)
I checked some of the publishers who use the `Unit.name` field (at least 36, see the list attached), and then checked the unique names used with this [colab](https://colab.research.google.com/drive/1z2hjpCOkBfm7c4XmzdiDwPwYdxiSWmjJ#scrollTo=EIjay57y0PAU) (and manually) and at least the following use some of the units as a unit of presentation:
1. armenia: ['piece' 'pill' 'bottle' 'package' 'box',  'set'  'dose'']
2. bolivia_agetic: PIEZA
3. chile: paquete, tira, bidón, pote, pan, among others
4. colombia: Caja x 12, Paquete x 12, Empaque de mínimo 480 rótulos, Paquete x 25, Caja, Frasco 20 tabletas, among others
5. costa_rica_poder_judicial_releases: [''Cajas' 'Paquetes' 'Envases' 'Pares'  'Resmas' 'Rollos' 'Bolsas''Láminas' 'Sacos' 'Juegos' 'Pliegos' 'Latas' 'Estañones' 'Piezas' 'Cubetas' 'Block']
6. ecuador_emergency: BARRIL
7. honduras_portal: caja, juego, rollo, resma, 
8. kenya_makueni: ['each' 'lot' 'ream' 'packet']
9. kyrgyzstan: Упаковка(package), Штука (piece), Дюжина рулонов (rolls)
10. mexico_administracion_publica_federal: juego, envase, lata, amolleta, among others
11. mexico_durango_idaip: ['Servicio' 'Pieza']
12. mexico_grupo_aeroporto: ['rll' 'pz' 'paq']
13. mexico_guanajuato_iacip: ['Servicio' 'Pieza']
14. mexico_inai_api: ['Servicio' 'Pieza']
15. mexico_nuevo_leon_cotai: ['Servicio' 'Pieza']
16. mexico_nuevo_leon_records: JUEGO, ROLLO, pza, EQUIPOS, jGO
17. mexico_veracruz_ivai: [ 'Pieza' 'Servicio']
18. mexico_yucatan_inaip: [ 'Pieza']
19. mexico_zacatecas_izai: [ 'Pieza']
20. moldova: bucata, Borcan, Doza, Coala de tipar
21. nigeria_abia_state: set
22. nigeria_budeshi_records: ['Pieces' 'Packs' 'copies' 'Cartons']
23. nigeria_ebonyi_state: ['Pieces' '5' 'Piece' 'set' 'pairs' 'sets']
24. uruguay: paquete, lata, potes, juegos, ampollas, among others
25. zambia: Ream 'packet' 'Pads' 'Pack' 'Bottle' 'box' 'ream' 'sets', rolls


* For reference: paquete: package, juegos: set, rollos: rolls, caja:  box, envases: container, bidón: drum, pote: pot, pieza: piece, servicio: service

So the answer is yes, at least 25 publishers sometimes use the `Unit.name` as a unit of presentation. But, we know this is a bad practice that difficult the unit prices comparison, so I think that instead of explicitly allowing both, we should allow (for compatibility) but discourage the use of this field as the unit of presentation.

**Comment by jpmckinney** [comment] 2022-02-02 18:34
How many publishers use it as a unit of measure?

**Comment by yolile** [comment] 2022-02-02 20:31
The ones who disclose the field and use it **only** as a unit of measure: 

1. argentina_buenos_aires
2. argentina_vialidad
3. kenya_makueni
4. nepal_dhangadhi (I'm struggling with the translations from Hindi to English but they seem to be units of measures)
5. paraguay_dncp

Note that the others also use the field as a unit of measure most of the time and as a unit of presentation fewer times.

Some of them uses other things that are not unit of measure or presentation, for example honduras_cost, mexico_mexico_city_infocdmx, slovenia, mexico_mexico_state_infoem, mexico_oaxaca_iaip (I'm not sure if we should consider "Service" and "Piece" as unit of presentation or something else, I guess the correct unit of measure should be "unit" for these cases)

**Comment by jpmckinney** [comment] 2022-02-02 22:23
Thanks. So if we were to narrow the semantics (via "discourage" to avoid backwards-incompatibility), then what is the alternative for disclosing the unit of presentation?

**Comment by yolile** [comment] 2022-02-02 22:34
I was thinking about incorporating the `container` object from the [medicine extension](https://extensions.open-contracting.org/en/extensions/medicine/master/schema/) but from https://github.com/open-contracting/standard/issues/1110#issuecomment-730064497 I see that we added the `weight`field to be used along with the unit name, where the unit name can be used as the unit of presentation 🤔

**Comment by jpmckinney** [comment] 2022-02-02 22:40
What's the problem? Seems okay to me.

**Comment by yolile** [comment] 2022-02-02 22:48
Well, the problem is that we will be using the unit as the unit of presentation and I was trying to avoid that :) and we will introduce some conditional semantics, I guess, e.g. if `weight` is present then the unit is a unit of presentation, otherwise it *probably* is a unit of measure

**Comment by jpmckinney** [comment] 2022-02-03 15:50
I'm not following. Can you share a full JSON example with each of the unit of measure and unit of presentation?

**Comment by jpmckinney** [comment] 2022-02-03 15:53
If you're worried about https://github.com/open-contracting/standard/pull/1125 – I never actually approved the changes, so we can just revert it. (All I did was get tests to pass.)

**Comment by yolile** [comment] 2022-02-08 13:15
E.g. to represent "50 liters of Juice in bottles of 10 liters each", with `weight` that will be:

``` json
{
    "items": [
        {
            "id": "1",
            "description": "Juice",
            "quantity": 50,
            "unit": {
                "name": "Bottle",
                "weight": {
                  "value": 10,
                  "unit": "LTR"
                }
            }
        }
    ]
}
```
Here, `unit.name` is a unit of presentation (Bottle), but if we want to represent "50 liters of Juice" no matter the package, then the JSON would be:

``` json
{
    "items": [
        {
            "id": "1",
            "description": "Juice",
            "quantity": 50,
            "unit": {
                "name": "Liters",
                "id": "LTR"
            }
        }
    ]
}
```
Where the `unit.name` and `unit.id` are units of measures. So, if we follow that approach, when `unit.weight` is present, the unit corresponds to a unit of presentation, and if not, the unit is a unit of measure.

But if we use `container` instead:

``` json
{
    "items": [
        {
            "id": "1",
            "description": "Juice",
            "quantity": 50,
            "unit": {
                "name": "Liters",
                "id": "LTR"
            },
            "container": {
              "name": "Bottle",
              "capacity": {
                "unit": {
                  "scheme": "UNCEFACT",
                  "id": "LTR"
                },
                "value": "10"
              }
          }
        }
    ]
}
```

Both, the unit of measure and the unit of presentation are preserved, but in two separated objects, and `items.unit` is always a unit of measure.

**Comment by jpmckinney** [comment] 2022-02-08 18:46
Hmm, well "litre" is not a unit of weight (a litre of mercury weighs more than of water). But anyway, we can change the example to be 10 packs of gum, where each pack weighs 50g.

I suggest that we revert #1125 and consider merging `container` from the medicine extension. And then we update the guidance to encourage using `unit` for unit of measure, and to use `container` for unit of presentation.

Users will still have to check the `unit`'s `id` and/or `name` to know whether it is a unit of measure or presentation, since older data (as we know) uses it for both meanings.

However, something we still need to figure out is the last example in the medicine extension, which follows this guidance: "If a medicine item is packaged in a multi-drug container, use items.quantity for the quantity in the container and items.unit for the unit." It doesn't use `unit` as a unit of measure.

**Comment by yolile** [comment] 2022-02-16 16:07
I opened PRs for the medicine extension and for reverting `weight`.

There are some items for which a unit of measure doesn't make sense. For example, pencils or the medicine described in the second example of the medicines extension. I think the `Item.unit` field should be omitted for these cases, as there is actually no info about the unit of measure. In that case, `quantity` will refer to the item itself and not to the unit of measurement.  One example with bananas:

I want `{quantity}` `{unit.name}` `{item.name}` packaged in `{container.name}` of `{container.capacity.value}` `{container.capacity.unit.id}` each:

quantity: 100
unit.name: KGM
item.name: banana
container.name: box
container.capacity.value: 10
container.capacity.unit.id: KGM

I want 100 KGM of bananas packaged in boxes of 10 KGM each.

I want 100 KGM of bananas packaged in boxes.

I want 100 KGM of bananas.

I want 100 bananas.

As you can see, `quantity` always refers to units, unless the `unit.name` is not present. Even if the unit.name is not present, the `unit.value` could be disclosed and always refer to one unit of `item.name`. We could consider if it will be useful to include the price per container as well.

**Comment by jpmckinney** [comment] 2022-02-16 18:15
Sounds good! This can also be used for: I want 100 bananas in boxes of 10 (bananas) each.

We can consider a `container.value` field, but we need some evidence of the demand.

@duncandewhurst, could you share your opinion on the modelling/semantics as well?

**Comment by duncandewhurst** [comment] 2022-02-17 03:51
This seems like a good solution that should make the data more usable for unit price comparisons.

'container' doesn't exactly fit for some cases, e.g. a reel of cable, but I see that is addressed by the description in the medicine extensions schema, although that will need updating so that it is not medicine-specific.

`container.name` uses a medicine-specific codelist, but for the general case UNCEFACT Recommendation 21 (Codes for Passengers, Types of Cargo, Packages and Packaging Materials (with Complementary Codes for Package Names)) seems a better fit.

**Comment by jpmckinney** [comment] 2022-02-17 17:39
> 'container' doesn't exactly fit for some cases, e.g. a reel of cable, but I see that is addressed by the description in the medicine extensions schema, although that will need updating so that it is not medicine-specific.

Since the medicine extension is new and not yet implemented, we can rename the field. Would `package` or `packaging` work?

**Comment by duncandewhurst** [comment] 2022-02-17 19:46
If we want to align with UNCEFACT Rec 21, the correct term would be `packageType`, since `package` refers to the container *and* its contained goods but we only want to describe the container.

Should we also consider an `id` and `scheme` for the package type?

After further reading, I'm not sure that unit of presentation and unit of packaging are actually the same thing, e.g. I want 1,000 paracetamol tablets presented in blister packs of 20 tablets packaged in boxes of 50 blister packs.

**Comment by yolile** [comment] 2022-02-22 20:21
> After further reading, I'm not sure that unit of presentation and unit of packaging are actually the same thing

For medicines, the term "container" is used to identify the **immediate** container for the medicine, that is, the package that is in direct contact with the medicine. 

> I want 1,000 paracetamol tablets presented in blister packs of 20 tablets packaged in boxes of 50 blister packs.

I guess we will need to investigate if this could be a real example, for example, if the last part is actually normally relevant (the "boxes of 50 blister packs" part). I think that need didn't come up during the medicine extension research, but we could investigate further

**Comment by duncandewhurst** [comment] 2022-02-28 02:16
Ah I see, the use cases for UNCEFACT Rec 21 are more about the outer packaging, which is of interest to freight companies and customs agencies etc.

**Comment by jpmckinney** [comment] 2022-03-11 19:22
[Directive 92/27/EEC](https://eur-lex.europa.eu/legal-content/en/ALL/?uri=CELEX%3A31992L0027) has:

- immediate packaging means the container or other form of packaging immediately in contact with the medicinal product
- outer packaging means the packaging into which is placed the immediate packaging

ISO 11239 (2012) has:

- container: item of packaging that is part of a medicinal product and is used for storage, identification and/or transport of the components of the medicinal product. NOTE “Container” is a general concept that groups together the concepts of immediate container, intermediate packaging and outer packaging.
- immediate container: immediate packaging in which a manufactured item or pharmaceutical product is contained and with which it is in direct contact. ... NOTE 2 A pharmaceutical dose form can fulfil the role of an immediate container, e.g. a capsule containing a powder for inhalation; the capsule in this case is not a container. NOTE 3 An alternative, compatible definition of immediate container (“immediate packaging”) is given in Directive 92/27/EEC.
- intermediate packaging: level of packaging between the outer packaging and the immediate container
- outer packaging: external container in which a medicinal product is supplied. NOTE 1 The manufactured item or pharmaceutical product is not in direct contact with the outer packaging except where the outer packaging also serves as the immediate container. NOTE 2 An alternative, compatible definition of outer packaging is given in Directive 92/27/EEC: “packaging into which is placed the immediate packaging”.

We definitely have evidence of demand for immediate packaging/container, since it is required for unit price comparison, for which there are many known researchers. I think the question here is:

1. If we go with `container` or `packaging`, then it might be confusing if we later add other types of container/packaging. So we can maybe consider `immediatePackaging` or `immediateContainer`.

I think we have no evidence of use cases for intermediate packaging. While we can easily imagine examples (blister packs in boxes on pallets), I don't know any procurement agency actually detailing such packaging in a structured format, and I'm fairly doubtful of who needs it in a structured format (bidders can just read such descriptions as text).

As for the outer packaging, while we can more easily imagine use cases (e.g. freight companies), I'm not sure that we have evidence of demand. From the supply side, while I think some countries have this data, I'm not sure whether the (imagined) use cases are really strong enough (hard to say which priority [user needs](https://standard.open-contracting.org/latest/en/guidance/design/user_needs/) are being met). That said:

2. I figure there might be cases where the publisher has data on packaging, but they don't know whether the packaging is immediate or outer. Should we provide a place for that information?

**Comment by duncandewhurst** [comment] 2022-03-14 19:41
> So we can maybe consider `immediatePackaging` or `immediateContainer`.

That seems like a useful clarification.

> I figure there might be cases where the publisher has data on packaging, but they don't know whether the packaging is immediate or outer. Should we provide a place for that information?

Perhaps we should wait until we have a real example before adding something to the schema. In the meantime, we can have a worked example page on containers and packaging, which can include some of the content from this discussion and can refer implementers to the helpdesk if they aren't sure what sort of packaging their data describes.

**Comment by jpmckinney** [comment] 2022-03-14 21:31
This issue covers a few things, but I think we can do one or more of:

1. Distinguish the unit of measurement from the unit of presentation, either or both in guidance and schema.
1. Update guidance/schema so that the existing `unit` is for the unit of measurement, and discourage its use for the unit of presentation. https://github.com/open-contracting/standard/issues/1343#issuecomment-1028414476
1. Add `immediatePackaging` for the unit of presentation, as that did come up a lot in the medicine extension research.

If we do (2), then I would prefer to have an option for unit of presentation (3).

At any rate, we can start by updating the medicine extension to stage the changes to the schema.

**Comment by duncandewhurst** [comment] 2022-03-14 23:44
Sounds good!

**Comment by odscjen** [comment] 2023-09-14 15:49
@jpmckinney checking if this is ready for PR in the medicine extension based on https://github.com/open-contracting/standard/issues/1343#issuecomment-1067316229?

**Comment by jpmckinney** [comment] 2023-09-20 19:13
Yes, ready!

**Comment by odscjen** [comment] 2023-11-28 15:15
To clarify what changes are to be made to the Medicine extension:

1. `Container` to be renamed `ImmediateContainer`
2. Update the description of `SimpleUnit` (as referenced within `Container`) to clarify that it should only be used for units of measurement and not units of presentation.

@jpmckinney is this all? The examples already only cover units of measurements

**Comment by jpmckinney** [comment] 2023-11-28 22:50
> 1. `Container` to be renamed `ImmediateContainer`

Yes, and the field and codelist as well. The only other candidate was `immediatePackaging`, but ISO 11239 (2012), at least, seems to prefer "container" for immediate ones and "packaging" for outer ones. Per https://github.com/open-contracting/standard/issues/1343#issuecomment-1065419798 and following comment, we don't presently have use cases for other types of containers/packaging.

> 2. Update the description of `SimpleUnit` (as referenced within `Container`) to clarify that it should only be used for units of measurement and not units of presentation.

I think the description in the medicine extension is already clear. That bullet was more about OCDS.

**Comment by odscjen** [comment] 2023-12-05 15:19
Moved this back into To do: Semantics, as the medicine extension has been updated as discussed but there remains the issue of updating guidance and description of `unit`

**Comment by odscjen** [comment] 2024-05-09 10:45
Thinking about what needs updated in core 1.2, from the above discussion it seems like the following is to be done to core OCDS:

1. Update the description of 'Unit' to clarify that it should only be used for units of measurement and not units of presentation.

But now there's nowhere for publishers to put units of presentation so

2. Add `ImmediateContainer` from the medicine extension to `Item`, will also require copying over `Quantity` and `SimpleUnit` - this is to provide a field to declare units of presentation. `Quantity` is `SimpleUnit` (`scheme` and `id`) plus `value` where `value` isn't monetary. This is what makes it different from `Unit` which explicitly says that `.value` is monetary.

3. Add a sentence of guidance to [Unit](https://standard.open-contracting.org/staging/1.2-dev/en/schema/reference/#unit) discouraging the use of `Unit` for units of presentation, and add a sub-section to [Item](https://standard.open-contracting.org/staging/1.2-dev/en/schema/reference/#item) explaining it's use for units of presentation

**Comment by jpmckinney** [comment] 2024-05-10 00:49
Yes that's correct! More or less the same list as in https://github.com/open-contracting/standard/issues/1343#issuecomment-1067316229 and following comments.

**Comment by odscjen** [comment] 2024-05-10 11:04
Great thanks, just wanted to clarify before I started a PR as this is a long and slightly twisty thread :)

**Comment by odscjen** [comment] 2024-05-10 12:12
Looking at the `immediateContainer.csv` codelist which will be getting added to the core standard as part of this it's very medicine specific and missing some obvious container types, e.g. "pallet", "drum", "reel". Is it worth doing some research to fill this codelist out to be more general and less medicine-centric?

**Comment by jpmckinney** [comment] 2024-05-10 16:04
Good catch. I would not reuse the medicine codelist (better to not have any codelist than to use that one).

For context, for medicine, we noted in readme:

> The `immediateContainer` codelist is a copy of the codes and titles from FHIR's [Medication Knowledge Package Type](https://terminology.hl7.org/CodeSystem/medicationknowledge-package-type/) codelist. Given that the terms are undefined in FHIR, the descriptions are copied from corresponding terms from the [EDQM Standard Terms database](https://standardterms.edqm.eu), reproduced with the permission of the European Directorate for the Quality of Medicines & HealthCare, Council of Europe (EDQM). The EDQM Standard Terms database is not a static list and content can change over time; the descriptions were retrieved on July 21, 2021.

If you can find existing standards for containers more generally, we can point to them, but without adding them as a codelist (unless they are really good quality). We can also point to the medicine codelist (if the items are medicines).

**Comment by odscjen** [comment] 2024-05-14 11:50
Having had a quick look around the only suitable codelist I could find is from GS1 GDSN which has a PackageTypeCodelist (see https://www.gs1.org/standards/gdsn/3-1-27 [Code List Document](https://www.gs1.org/docs/gdsn/3.1/GDSN_and_Shared_Code_Lists_3p1p27_March_12_2024.xlsx) for the current version). This is the organization that creates barcodes for trade and seem good quality and stable so we could reference that, or just not reference anything (other than the medical one for medicines)

**Comment by jpmckinney** [comment] 2024-05-14 16:30
Yeah, looks decent (extracted below). What is the copyright (or terms and conditions) on the list? I'm thinking whether to include it in OCDS as an external codelist. At any rate, we can link to it.

<details>

| Code | Title | Description |
| - | - | - |
| AA | Intermediate Bulk Container, rigid plastic | "A Rigid Intermediate Bulk Container (RIBC) that is attached to a pallet or has the pallet integrated into the RIBC. The container is used for the transport and storage of fluids and other bulk materials. The construction of the IBC container and the materials used are chosen depending on the application.  There are various types available in the market place. Foldable (collapsible) IBC Container, Plastic composite IBC Container, Wire Cage IBC Container, Steel IBC Container, and Stainless steel IBC Container." |
| AE | Aerosol | A gas-tight, pressure-resistant container with a valve and propellant. When the valve is opened, propellant forces the product from the container in a fine or coarse spray pattern or stream. (e.g., a spray can dispensing paint, furniture polish, etc, under pressure). It does not include atomizers, because atomizers do not rely on a pressurised container to propel product from the container. |
| AM | Ampoule | A relatively small container made from glass or plastic tubing, the end of which is drawn into a stem and closed by fusion after filling. The bottom may be flat, convex, or drawn out. An ampule is opened by breaking the stem. |
| BA | Barrel | A cylindrical packaging whose bottom end is permanently fixed to the body and top end (head) is either removable or non-removable. |
| BBG | Bag in Box | Bag-In-Box or BIB is a type of container for the storage and transportation of liquids. It consists of a strong bladder, usually made of aluminium PET film or other plastics seated inside a corrugated fibreboard box. The box and internal bag can be fused together. In most cases there is nozzle or valve fixed to the bag. The nozzle can be connected easily to a dispensing installation or the valve allows for convenient dispensing. |
| BG | Bag | A preformed, flexible container, generally enclosed on all but one side, which forms an opening that may or may not be sealed after filling. |
| BJ | Bucket | A container, usually cylindrical, can be equipped with a lid and a handle. (e.g., a pail made of metal, plastic, or other appropriate material). |
| BK | Basket | A semi rigid container usually open at the top traditionally used for gathering, shipping and marketing agricultural products. |
| BL | Berlingot | Packaging most often tetrahedral or cylindrical in shape used to contain liquids. |
| BO | Bottle | A container having a round neck of relatively smaller diameter than the body, as compared with a jar, and an opening capable of holding a closure for retention of the contents. The cross section of the bottle may be round, oval, square, oblong, or a combination of these. Bottles generally are made of glass or plastics but can also be earthenware or metal. Bottle may be disposable, recyclable, returnable, or reusable. |
| BPG | Blister pack | A type of packaging in which the item is secured between a preformed (usually transparent plastic) dome or “bubble” and a paperboard surface or “carrier.” Attachment may be by stapling, heat- sealing, gluing, or other means. In other instances, the blister folds over the product in clam-shell fashion to form an enclosing container. Blisters are most usually thermoformed from polyvinyl chloride; however, almost any thermoplastic can be thermoformed into a blister. |
| BRI | Brick | A rectangular-shaped, stackable package designed primarily for liquids such as juice or milk |
| BX | Box | A non-specific term used to refer to a rigid, three- dimensional container with closed faces that completely enclose its contents and may be made out of any material. Even though some boxes might be reused or become resealed they could also be disposable depending on the product hierarchy. |
| CG | Cage | A container enclosed on at least one side by a grating of wires or bars that lets in air and light. |
| CHB | Chub | A chub or a chub pack is a type of container formed by a tube of flexible, non-edible packaging material. The cylindrical package has the appearance of a sausage with the ends sealed by metal crimps or clips, e.g. for sausages (artificial intestine). |
| CM | Card | A flat package to which the product is hung or attached for display. |
| CMS | Clam Shell | A one-piece container consisting of two halves joined by a hinge area which allows the structure to come together to close. Clamshells get their name from their appearance to the shell of a clam, which it resembles both in form and function. |
| CNG | Can/Tin | A metallic and generally cylindrical container of unspecified size which can be used for items of consumer and institutional sizes. |
| CP | Capsule | Small packaging element generally cylindrical with round edges and containing any substances like liquids, small objects like toys, coffee capsules. |
| CQ | Cartridge | A container holding a item or substance, designed for insertion into a mechanism. Examples: Ink. Beverage Syrup. |
| CR | Crate | A non-specific term usually referring to a rigid three- dimensional container with semi-closed faces that enclose its contents for shipment or storage. Crates could have an open or closed top and may have internal divers. Even though some crates might be reused or become resealed they could also be disposable depending on the product hierarchy. |
| CS | Case | A non-specific term for a container designed to hold, house, and sheath or encase its content while protecting it during distribution, storage and/or exhibition. Cases are mostly intended to store and preserve its contents during the product's entire lifetime. |
| CT | Carton | A non-specific term for an open or re-closable container used mostly for perishable foods (e.g. eggs, or fruit). |
| CU | Cup/Tub/Bowl | A flat-bottomed container that has a base of any shape and which may or not be closed with a lid. Usually made of paper, plastic or other materials these containers are typically used to contain mostly (but not exclusively) foods such as ice cream, margarine, yogurt, sour cream, confections, etc. |
| CY | Cylinder | A rigid cylindrical container with straight sides and circular ends of equal size. |
| EN | Envelope | A predominantly flat container of flexible material having only two faces, and joined at three edges to form an enclosure. The non-joined edge provides a filling opening, which may later be closed by a gummed or adhesive flap, heat seal, tie string, metal clasp, or other methods. |
| GTG | Gable Top | A rectangular-shaped, non-stackable package designed primarily for liquids such as juice or milk |
| HG | Hanger | A support for hanging products. Can be curved, triangular, or other various shapes. |
| JG | Jug | A container, normally cylindrical, with a handle and/or a lid or spout for holding and pouring liquids |
| JR | Jar | A rigid container made of glass, stone, earthenware, plastic or other appropriate material with a large opening, which is used to store products, (e.g., jams, cosmetics). |
| MPG | Multipack | A bundle of products held together for ease of carriage by the consumer. A multipack is always a consumer unit. |
| NE | Not packed | The item is provided without packaging. |
| NT | Net | A container of meshwork material made from threads or strips twisted or woven to form a regular pattern with spaces between the threads that is used for holding, carrying, trapping, or confining something. |
| PB | Pallet Box | A three-dimensional container which either has a pallet platform permanently attached at its base or alternatively requires a platform for its handling and storage as due to its constitution it cannot be handled without it. The characteristics of the platform should be specified using the pallet type code list |
| PLP | Peel Pack | A package used for sterile products which may be torn open without touching the product inside. |
| PO | Pouch | A preformed, flexible container, generally enclosed with a gusset seal at the bottom of the pack can be shaped/arranged to allow the pack to stand on shelf. |
| PT | Pot | A flat-bottomed container that has a base of any shape and which may or not be closed with a lid. Pots are usually made of cardboard, plastic, ceramic, metal or other materials and may be used for a wide array of products such as cosmetics, food/liquids, dairy products, plants. |
| PU | Tray | A shallow container, which may or may not have a cover, used for displaying or carrying items. |
| PUG | Packed, unspecified | Packaging of the product (or products) is currently not on the list. Use this code when no suitable options are available and only while a Change Request is approved for the proper packaging type. |
| PX | Pallet | A platform used to hold or transport unit loads. |
| RK | Rack | A non specific term identifying a framework or stand for carrying, holding, or storing items. Commonly on wheels and primarily used in the logistical functions to deliver items such as hanging garments, or items on shelves such as dairy products and bakery items and flowers. |
| RL | Reel | A spool on which thread, wire, film, etc, is wound. Any device on which a material may be wound. Usually has flanged ends and is used for shipping or processing purposes. |
| RO | Roll | Roll |
| SG | Syringe | Device consisting of a piston and a cylindrical pump body, which is used for administering, for example a liquid or joint compound. |
| STR | Stretchwrapped | In packaging, a high-tensile plastic film, stretched and wrapped repeatedly around an item or group of items to secure and maintain unit integrity. The use of stretch film to tightly wrap a package or a unit load in order to bind, protect and immobilize it for further handling or shipping. |
| SW | Shrinkwrapped | In packaging, a plastic film around an item or group of items which is heated causing the film to shrink, securing the unit integrity. The use of shrunken film to tightly wrap a package or a unit load in order to bind, protect and immobilize it for further handling or shipping. |
| SY | Sleeve | A non-rigid container usually made of paper, cardboard or plastic, that is open-ended and is slid over the contents for protection or presentation. |
| TU | Tube | A cylindrical container sealed on one end that could be closed with a cap or dispenser on the other end. |
| WIRE | Wire | A packaging made of a non-specific material in the form of very flexible thread or slender rod. |
| WRP | Wrapper | The process of enclosing all or part of an item with layer(s) of flexible wrapping material (e.g., for an individually packed ice cream). Includes gas-tight packs (e.g. for sausages). Does not include items which are shrink-wrapped or vacuum-packed. |
| X11 | Banded package | Something used to bind, tie, or encircle the item or its packaging to secure and maintain unit integrity. |
| ZU | Flexible Intermediate Bulk Container | A non-rigid container used for transport and storage of fluids and other bulk materials. The construction of the IBC container and the materials used are chosen depending on the application. |

</details>

**Comment by odscjen** [comment] 2024-05-15 10:11
The only thing I could find around the T&C or copyright of the standard (and therefore it's codelists) is the [GS1 Intellectual Property Policy](https://www.gs1.org/standards/ip), from the [GS1 IP made simple](https://www.gs1.org/docs/gsmp/GS1_Intellectual_Property_Policy_Made_Simple.pdf) pdf it seems that to make use of the codelist within OCDS OCP would need to sign up to the IPP, but it's unclear how that would then interact with the open aspect of OCDS? 

There's also their website (i.e. where the standard can be accessed) terms of use which states:

> The content of this web site is copyright protected. You may download, display, print and reproduce this material in unaltered form only (retaining this notice) for your personal, non-commercial use or use within your organisation. Apart from any use as permitted under Belgian Copyright law, all other rights are reserved. Requests and inquiries concerning reproduction and rights should be addressed to: GS1, 326 Avenue Louise, 1050 Brussels, Belgium, E-mail: [contactus@gs1.org](mailto:contactus@gs1.org).
> 
> This notice is not to be erased. You are not permitted to re-transmit, distribute or commercialise the information or material without seeking prior written approval from GS1.

I think the sensible options are either to contact GS1 directly to ask or just to reference the list without including it as an external codelist.

**Comment by jpmckinney** [comment] 2024-05-15 13:45
Sounds good - let's just reference it for now.

**Closed as completed** 2024-06-28 20:08 UTC
Labels: Semantics, Ready for PR
