### ISSUE TITLE
Bug fix releases for OCDS 1.1 and 1.0 - 7 day comment period

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#521] opened 2017-07-31 10:05 UTC
Bug fix (patch) releases of OCDS 1.1 and 1.0 are now staged and ready for review.

You will find OCDS 1.1.1 at http://standard.open-contracting.org/1.1.1-dev/en/ with a [changelog here](http://standard.open-contracting.org/1.1.1-dev/en/schema/changelog/) and pasted below. Please use [GitHub issue #520](https://github.com/open-contracting/standard/pull/520) to raise any questions or concerns about this patch release.

OCDS 1.0.3, with minor fixes, is found at http://standard.open-contracting.org/1.0.3-dev/en/ with a [changelog here](http://standard.open-contracting.org/1.0.3-dev/en/schema/changelog/). Please use [GitHub issue 514](https://github.com/open-contracting/standard/pull/514) to raise any questions or concerns about this patch release. 

Patch releases are backwards compatible (or correct unintentional errors in earlier schema or documentation releases), and so do not go through the full upgrade process. These patch releases will become the main versions for 1.1 and 1.0 in 7 days, unless substantive objections are raised. 

This should not impact on existing published data (apart from where schema errors have been causing validation problems), although publishers may wish to review the changelog to identify areas where they can improve the alignment of values to updated open codelists. 

(Please note, Spanish translations have not yet been updated for 1.1.1. The 1.0.3 changes have no impact on translations.)

Best regards,

Tim Davies

### Bug fixes

* [#482](https://github.com/open-contracting/standard/issues/482) **[Allow parties.role to be set to null](https://github.com/open-contracting/standard/pull/502/commits/475abf598063aae5c22e07baba015d960fcc3a95)** - required by the [merging approach](http://standard.open-contracting.org/1.1.1-dev/en/schema/merging/). 
* [#422](https://github.com/open-contracting/standard/issues/422) **[Including currency codelist in documentation and schema](http://standard.open-contracting.org/1.1.1-dev/en/schema/codelists/#currency)** to support validation of currency values.
* [#479](https://github.com/open-contracting/standard/issues/479) **[Fixing incorrect requirement to include releases in record-package-schema.json](http://standard.open-contracting.org/1.1.1-dev/en/schema/record_package/)** 
* [#475](https://github.com/open-contracting/standard/issues/475) **Adding enum arrays to all fields in the schema with a closed codelist** to support validation.

### Minor revisions

* [#471](https://github.com/open-contracting/standard/issues/471) **[Updating milestoneType codelist](http://standard.open-contracting.org/1.1.1-dev/en/schema/codelists/#milestone-type)** replacing 'planning' with 'preProcurement' and 'adjudication' with 'assessment' and introducing codes for 'approval' and 'financing'. This is an open codelist, so previous codes remain valid, but publishers able to update to the new codes should do so. 
* [#473](https://github.com/open-contracting/standard/issues/473) **[Updating definition of contractSchedules in documentType codelist](http://standard.open-contracting.org/1.1.1-dev/en/schema/codelists/#document-type)**

### Documentation improvements

* **Fixing typographic errors throughout the documentation and codelist descriptions**
* [#480](https://github.com/open-contracting/standard/pull/480/commits/c3c41225639a06b0b0552016b32e2fe2e901a8fe) **[Updating basic, intermediate, advanced](http://standard.open-contracting.org/1.1.1-dev/en/implementation/levels/) publication guidance** - to ensure tables and text are aligned. 
* [#489](https://github.com/open-contracting/standard/issues/489) **Listing the milestone documents extension as a core extension** - and removing it from the community extensions list. This extension is only needed by publishers with legacy data containing documents at the milestone level.
* [#493](https://github.com/open-contracting/standard/issues/493) **[Updating the description of the Organization Identifier Scheme codelist](http://standard.open-contracting.org/1.1.1-dev/en/schema/codelists/#organization-identifier-scheme)** to reflect that the codelist is now maintained by [org-id.guide](http://www.org-id.guide/).

### Code and build process

* [#506](https://github.com/open-contracting/standard/issues/506) **Removed make_field_definitions.py** from utility scripts as it is no longer required.
* **Addition of docstrings to key scripts**

## 1.0.3 Changelog

* [#329](https://github.com/open-contracting/standard/issues/329) - updated ```item.quantity``` to support decimal values (integer -> number)
* [#253](https://github.com/open-contracting/standard/issues/253) - updated ```value.amount``` to support negative values

**Comment by mireille-raad** [comment] 2017-08-14 06:29
I was checking http://standard.open-contracting.org/1.1.1-dev/en/implementation/levels/#how-to-publish-5-approach 

> The documentation on flat CSV file serialization of the standard, and the **OCDS mapper**, may be useful for those seeking to publish at this level.

I visited the link to OCDS mapper and it is no longer supported - https://github.com/open-contracting-archive/mapper 
Maybe remove the reference or link to something that is supported ?

**Comment by mireille-raad** [comment] 2017-08-14 06:38
For the different levels of publication

☆ ☆ Provide machine-readable data about contracts

Maybe you can add something about creating a basic/friendly user interface that allows end users to search, see analytics on procurements and summaries of contracts (something along those line)

This can add some focus on end users needs and not just a 100% pure data oriented approach.

If you think this is not suitable for this stage, then maybe at the next or in the "Stepping up" section

**Comment by mireille-raad** [comment] 2017-08-14 06:42
![levels_en](https://user-images.githubusercontent.com/521705/29260754-82901814-80d4-11e7-8f3a-3e34098a49c9.png)

This image is a bit cluttered. 

It might be nice to create individual "Cards" or "Badges" about the different publication levels. Each card will then have a cleaner look and will be visually nice and fancy.

**Comment by mireille-raad** [comment] 2017-08-14 06:47
Broken link on "established protocols" - it leads to a 404 on http://standard.open-contracting.org/1.1.1-dev/en/implementation/levels/hosting#discovery-and-apis (not sure if will be automatically fixed once this is moved out of dev)

☆ ☆ ☆ ☆ Use best practices for data on the web
[...]
Use **established protocols** to support discovery of your data, and to provide atom feeds of recently updated data. At this level, publishers may also expose data through an API, following community established conventions for API operation.

------------------

Broken link on JSON schema - it leads to a 404 http://standard.open-contracting.org/1.1.1-dev/en/implementation/schema/reference 
 
☆ ☆ ☆ Provide structured data using open standards
[...]
OCDS provides guidance on the fields to include, and how to structure them using a **JSON schema** so that third-parties can re-use your data effectively.

**Comment by mireille-raad** [comment] 2017-08-14 07:04
☆ ☆ ☆ ☆ Use best practices for data on the web

[...] 
This will allow users to follow the links to discover more about the context of the contracting processes they are exploring, **and will allow big-data analysis linking in these different datasets.** For example, following links to a company register to discover whether a company awarded a contract has been dissolved, or following links to budget and spending information.

### seriously.... don't use buzzwords.... big data analysis???
Implementation guidance is usually very down to earth, buzzwords are for blog posts.

The problem is with 2 parts of this sentence:
Big data: can you provide examples of extremely large government data sets, something in petabytes?

big-data analysis linking in these different datasets: is there a type of analysis called big data analysis?  I know some types of analysis have better results if you have large datasets... but doesn't make it big data analysis. Also how is big data analysis used to link datasets? 

The example you gave about company registry is not big data analysis, barely string matching.

**Comment by jpmckinney** [comment] 2017-08-26 00:44
Just noting that http://standard.open-contracting.org/latest/en/implementation/levels/ is more likely to undergo an overhaul than a tweak #388. That said, the [two broken links](https://github.com/open-contracting/standard/issues/521#issuecomment-322112082) should be fixed.

**Comment by jpmckinney** [comment] 2017-08-26 00:49
I'll open a new issue for the broken links. The upgrades have been merged. #388 now links here regarding the comments about revisions to `levels.md`, which wasn't part of the upgrade (there haven't been substantive changes since 1.0).

**Closed as completed by jpmckinney** 2017-08-26 00:49 UTC
